apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-tls-cert-monitoring
  namespace: monitoring
spec:
  secretName: nginx-tls-secret-monitoring  # Secret where the cert will be stored
  issuerRef:
    name: letsencrypt-prod  # Reference to the same ClusterIssuer
    kind: ClusterIssuer
  commonName: issy.site
  dnsNames:
    - issy.site
    - prometheus.issy.site
    - grafana.issy.site
