apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - {{ .Values.grafana.persistence.accessmode }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
  volumeMode: Filesystem
  storageClassName: nfs-grafana-class
