apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-grafana-pv
  namespace: monitoring
spec:
  capacity:
    storage: {{ .Values.grafana.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # NFS supports ReadWriteMany access mode
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-grafana-class
  nfs:
    path: /data/grafana  # The NFS directory for Nginx
    server:  192.168.1.165  #  NFS server address
