apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-grafana-pv
  namespace: monitoring
spec:
  capacity:
    storage: {{ .Values.grafana.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.grafana.persistence.accessmode }}  # NFS supports ReadWriteMany access mode
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-grafana-class
  nfs:
    path: {{ .Values.grafana.persistence.nfspath }}  # The NFS directory for Nginx
    server:  {{ .Values.grafana.persistence.nfsserver }}  #  NFS server address
