apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-grafana-class
  namespace: monitoring
provisioner: cluster.local/nfs
parameters:
  server: {{ .Values.grafana.persistence.nfsserver }} #  NFS server address
  path: {{ .Values.grafana.persistence.nfspath }}
