apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
  template:
    metadata:
      labels:
        k8s-app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.3.1
          ports:
            - containerPort: 9100
              protocol: TCP
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 200m
      serviceAccountName: prometheus-sa
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"  # This allows the pod to be scheduled on the control plane node

---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    k8s-app: node-exporter
spec:
  selector:
    k8s-app: node-exporter  # Ensure this matches the label of the node-exporter pods
  ports:
    - port: 9100
      targetPort: 9100
      name: metrics


