apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # namespace: monitoring
  name: prometheus-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["prometheuses", "servicemonitors", "podmonitors", "alertmanagers"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
