apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.listen-address=:9090"
            - "--web.external-url=http://{{ .Values.prometheus.domainname }}/prometheus"
            - "--web.route-prefix=/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/prometheus
              name: config-volume
              readOnly: true
            - mountPath: /prometheus
              name: prometheus-data
    restartPolicy: Always
    volumes:
      - name: config-volume
        configMap:
          name: prometheus-server-conf
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-pvc
        
