apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-rolebinding
  namespace: monitoring 
subjects:
- kind: ServiceAccount
  name: prometheus-sa  # Ensure it matches the service account name
  namespace: monitoring
roleRef:
  kind: Role
  name: prometheus-role  # Ensure it matches the role name
  apiGroup: rbac.authorization.k8s.io
