## Nginx Ingress
## Follow https://devopscube.com/setup-ingress-kubernetes-nginx-controller/

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ui
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/secure-backends: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  # Use the host you used in your kubernetes Ingress Configurations
  - host:  prometheus.{{ .Values.prometheus.image.domainname }}
    http:
      paths:
      - backend:
          service:
            name: prometheus-service
            port:
              number: {{ .Values.prometheus.service.port }}
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - prometheus.{{ .Values.prometheus.image.domainname }}  # Your Prometheus domain
      secretName: nginx-tls-secret-monitoring