apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-prometheus-pv
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # NFS supports ReadWriteMany access mode
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-prometheus-class
  nfs:
    path: /data/prometheus  # The NFS directory for Nginx
    server:  192.168.1.165  #  NFS server address
