apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-prometheus-pv
  namespace: monitoring
spec:
  capacity:
    storage: {{ .Values.prometheus.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.prometheus.storage.accessmode }}  # NFS supports ReadWriteMany access mode
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-prometheus-class
  nfs:
    path: {{ .Values.prometheus.storage.nfspath }}  # The NFS directory for Nginx
    server:  {{ .Values.prometheus.storage.nfsserver }}  #  NFS server address
