apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - {{ .Values.prometheus.storage.accessmode }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}
  volumeMode: Filesystem
  storageClassName:  nfs-prometheus-class
