apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: monitoring  
  name: prometheus-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
