# Default values for grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafana:
  replicaCount: 1
  image:
    repository: grafana/grafana
    tag: 8.2.5
  env:
    GF_SERVER_ROOT_URL: "https://issy.site/grafana"  # Make Grafana aware of the base path
    GF_SERVER_SERVE_FROM_SUB_PATH: "true"  # Enable Grafana to serve content from a subpath like /grafana
  service:
    type: ClusterIP
    port: 3000
  persistence:
    enabled: true
    size: 10Gi
    nfsserver: 192.168.1.165 # NFS server address
    nfspath: "/data/grafana"
    accessmode: "ReadWriteMany"
