apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-role
rules:
- apiGroups: [""]
  resources:
    - pods
    - nodes
    - nodes/proxy
    - nodes/metrics
    - services
    - endpoints
    - namespaces
    - persistentvolumes
    - persistentvolumeclaims
    - configmaps
    - secrets
    - replicationcontrollers
    - resourcequotas
    - limitranges
    - horizontalpodautoscaler
    - cronjob
    - poddisruptionbudget
    - apiservers

  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
    resources:
      - nodes/metrics
      - pods/metrics
    verbs: ["get", "list", "watch"]

- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-role
subjects:
- kind: ServiceAccount
  name: prometheus-sa
  namespace: monitoring
