apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # namespace: monitoring  
  name: prometheus-role
rules:
  - apiGroups: [""]
    resources: 
    - pods
    - nodes
    - services
    - namespaces
    - persistentvolumes
    - persistentvolumeclaims
    - configmaps
    - secrets
    - replicationcontrollers
    - resourcequotas
    - limitranges
    - horizontalpodautoscaler
    - cronjob
    - poddisruptionbudget
    - apiservers
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: 
    - endpoints
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
    - ingresses
    - networkpolicies
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
    - jobs
    - cronjobs
    verbs: ["get", "list", "watch"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
    - deployments
    - statefulsets
    - replicasets
    - daemonsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - volumeattachments
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["get", "list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - nodes/metrics
      - pods/metrics
    verbs: ["get", "list", "watch"]
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - prometheus
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: 
    - poddisruptionbudgets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources:
    - deployments
    - replicasets
    - ingresses
    verbs: ["get", "list", "watch"]
