apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # namespace: monitoring  
  name: prometheus-role
rules:
  # Permissions for core resources like pods, nodes, and services
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - namespaces
      - persistentvolumes
      - persistentvolumeclaims
      - configmaps
      - secrets
      - replicationcontrollers
      - resourcequotas
      - limitranges
      - horizontalpodautoscalers
      - cronjob
      - poddisruptionbudget
      - apiservers
    verbs: ["get", "list", "watch"]

  # Specific permissions for accessing `endpoints` and `apiservers`
  - apiGroups: [""]
    resources:
      - endpoints
      - apiservers  # Ensure access to apiservers resource for scraping metrics
    verbs: ["get", "list", "watch"]

  # Other resources for networking, batch, certificates, apps, and more
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

  - apiGroups: ["metrics.k8s.io"]
    resources:
      - nodes/metrics
      - pods/metrics
    verbs: ["get", "list", "watch"]

  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - prometheus
    verbs: ["get", "list", "watch"]

  # More resources for policy and extensions
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list", "watch"]

  - apiGroups: ["extensions"]
    resources:
      - deployments
      - replicasets
      - ingresses
    verbs: ["get", "list", "watch"]
  
