apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Name of the custom role
  name: prometheus-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch", "get"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "watch", "get"]
