apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: {{ .Values.kubestatemetrics.name }}
    app.kubernetes.io/version: {{ .Values.kubestatemetrics.tag }}
  name: kube-state-metrics
  namespace: monitoring
