apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
    - port: "9100"  # This should match the port exposed by node-exporter
      interval: 30s  # Scraping interval
      scheme: http   # Default scheme for scraping metrics
      path: /metrics # Path for metrics (default for node-exporter)
